stages:
  - analysis
  - build
  - deploy

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_manylinux_2_28:
  tags: ["manylinux_2_28"]

.tags_win10:
  tags: ["eo", "win10", "arepytools-win"]

.tags_deploy:
  tags: ["eo", "deploy"]

# === analysis ===============================================================
# ============================================================================
check_code_compliance_ruff:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s check_format

check_code_compliance_pylint:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s pylint

# === build ==================================================================
# ============================================================================
sdist:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_sdist
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.tar.gz

wheel:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_wheel
  artifacts:
    expire_in: 2 weeks
    paths:
      - dist/*.whl

doc:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - yum install -y pandoc
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_doc
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - docs/build/*.zip

# === deploy =================================================================
# ============================================================================
deploy_package:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - eval "$(ssh-agent -s)"
    - for file in dist/*.tar.gz dist/*.whl; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/eo_products/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/eo_products/archive;
      done

deploy_doc:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
    - if: '$DEPLOY_DOC == "true"'
  before_script:
    - export PACKAGE_VERSION=v$(grep "__version__" src/eo_products/__init__.py | awk -F '"' '{print $2}')
  script:
    - eval "$(ssh-agent)"
    - cat "$DASHBOARD_PRIVATE_KEY" | base64 -d | ssh-add -
    - for file in docs/build/*.zip; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/eo_products/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/eo_products/archive;
      done
    - unzip docs/build/*.zip
    - mv *eo_products*-html-doc ${PACKAGE_VERSION}
    - rsync --stats -r ${PACKAGE_VERSION} sardashboard@intranet.aresys.it:develop/eo_products/docs
    - ssh sardashboard@intranet.aresys.it "cd develop/eo_products/docs && rm latest && ln -s ${PACKAGE_VERSION} latest"