name: eo_products

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - "eo-products-v*"
    paths:
      - ".github/workflows/eo_products.yml"
      - "src/eo_products/**"
      - "tests/**"
      - "pyproject.toml"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/eo_products.yml"
      - "src/eo_products/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - run: echo "/opt/python/cp312-cp312/bin" >> $GITHUB_PATH
      - run: python -m pip install ruff
      - run: python -m ruff --version
      - run: python -m ruff format --check .
      - run: python -m ruff check .

  pylint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - run: echo "/opt/python/cp312-cp312/bin" >> $GITHUB_PATH
      - run: python -m pip install pylint
      - run: python -m pylint --version
      - run: python -m pylint src/eo_products

  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - run: echo "/opt/python/cp312-cp312/bin" >> $GITHUB_PATH
      - run: uv build --sdist --wheel .
      - uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist/
          retention-days: 14

  docs_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - run: python -m pip install ".[doc]"
      - run: python tools/build_doc.py
      - uses: actions/upload-artifact@v5
        with:
          name: documentation-site
          path: site/
          retention-days: 14
      - uses: actions/upload-artifact@v5
        with:
          name: documentation-archive
          path: documentation*.zip
          retention-days: 14

  docs_publish:
    if: startsWith(github.ref_name, 'eo-products-v')
    needs: docs_build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download docs site
        uses: actions/download-artifact@v4
        with:
          name: documentation-site
          path: site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    needs: [ruff, pylint, build]
    if: startsWith(github.ref_name, 'eo-products-v')

    runs-on: ubuntu-latest

    environment: eo-products-pypi

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Clean dist
        run: |
          find dist -type f ! -name "*.whl" ! -name "*.tar.gz" -delete

      - name: Show artifacts
        run: |
          find dist -type f -maxdepth 2

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
